# Generated by Django 4.0.4 on 2022-05-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('citizenship', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('meternum', models.CharField(default=None, max_length=200, unique=True)),
                ('previousunit', models.BigIntegerField(default=0)),
                ('currentunit', models.BigIntegerField(default=0)),
                ('discountamount', models.BigIntegerField(default=0)),
                ('fineamount', models.BigIntegerField(default=0)),
                ('totaldue', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('fine', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('citizenship', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
