# Generated by Django 4.0.4 on 2022-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customers_meternum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='meternum',
            field=models.BigIntegerField(default=None, unique=True),
        ),
    ]
